name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build & Test (x86_64)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies & QC Lab
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .

      # - name: Run tests
      #   run: |
      #     pip install pytest
      #     pytest


  # test-arm:
  #   name: Build & Test (ARM64 via QEMU)
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Register QEMU emulators
  #       uses: docker/setup-qemu-action@v2
  #       with:
  #         platforms: linux/arm64

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Build ARM64 Docker image
  #       run: |
  #         docker buildx build \
  #           --platform linux/arm64 \
  #           --load \
  #           -t qc_lab-arm64 .

